title: Mostly Harmless Coding
email: anthony@lethuillier.net
description: >-
  A companion website for my youtube channel dedicated
  to the developement of indie video games.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Harmless_Astro
github_username:  Anthony-MostlyHarmless

# Build settings
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme 

navbar-links:
  Home: "index"
  About: "about"
